# Generated by Django 2.1.3 on 2019-04-01 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('appliance_type', models.CharField(choices=[('air conditioner', 'Air conditioner'), ('air purifier', 'Air purifier'), ('ceiling fan', 'Ceiling fan'), ('dishwasher', 'Dishwasher'), ('hair dryer', 'Hair dryer'), ('microwave oven', 'Microwave oven'), ('other', 'Other'), ('refrigerator', 'Refrigerator'), ('vacuum Cleaner', 'Vacuum Cleaner'), ('washing machine', 'Washing machine'), ('water heater', 'Water heater'), ('water purifier', 'Water purifier')], max_length=50)),
                ('appliance_brand', models.CharField(choices=[('bajaj', 'Bajaj'), ('blue star', 'Blue Star'), ('carrier', 'Carrier'), ('godrej', 'Godrej'), ('haier', 'Haier'), ('hitachi', 'Hitachi'), ('ifb', 'IFB'), ('lg', 'LG'), ('mi', 'MI'), ('onida', 'Onida'), ('other', 'Other'), ('panasonic', 'Panasonic'), ('philips', 'Philips'), ('samsung', 'Samsung'), ('sharp', 'Sharp'), ('sony', 'Sony'), ('toshiba', 'Toshiba'), ('voltas', 'Voltas'), ('whirlpool', 'Whirlpool')], max_length=50)),
                ('appliance_model', models.CharField(max_length=50)),
                ('warranty', models.CharField(choices=[('pre warranty', 'Pre Warranty'), ('post warranty', 'Post Warranty')], max_length=50)),
                ('problem_description', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_date', models.DateField()),
                ('verfication_status', models.BooleanField(default=False)),
            ],
        ),
    ]
