# Generated by Django 2.1.3 on 2019-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='service_man',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
