# Generated by Django 2.1.3 on 2019-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0003_auto_20190402_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='charge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
