# Generated by Django 2.1.3 on 2019-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0004_clientrequest_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
