# Generated by Django 2.1.3 on 2019-04-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0005_clientrequest_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='problem_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
