# Generated by Django 2.1.3 on 2019-04-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0006_auto_20190405_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='request_status',
            field=models.CharField(choices=[('verification_pending', 'Verification pending'), ('verification_done', 'Verification Done'), ('service_done', 'Service Done')], default='verification_pending', max_length=50),
        ),
    ]
