# Generated by Django 2.1.3 on 2019-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0007_clientrequest_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='request_status',
            field=models.CharField(blank=True, choices=[('service_done', 'Service Done')], max_length=50, null=True),
        ),
    ]
