# Generated by Django 2.1.3 on 2019-04-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_request', '0008_auto_20190406_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='request_status',
            field=models.CharField(blank=True, choices=[('service_done', 'Service Done'), ('service_pending', 'Service Pending')], max_length=50, null=True),
        ),
    ]
